# Makefile for libthermo - MinGW64
CC         = gcc
AR         = ar
ARFLAGS    = rcs
CFLAGS     = -O2 -Wall -I. -Iinclude -I.. -DGCC

SRCDIR     = src
OBJS       = $(SRCDIR)/load.o $(SRCDIR)/thermo.o

LIBNAME    = libthermo.a

all: $(LIBNAME)

$(SRCDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBNAME): $(OBJS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

clean:
	del /f /q $(SRCDIR)\*.o

deep-clean: clean
	del /f /q $(LIBNAME)
